export const TRIP_LIST_REQUEST = "TRIP_LIST_REQUEST";
export const TRIP_LIST_SUCCESS = "TRIP_LIST_SUCCESS";
export const TRIP_LIST_FAIL = "TRIP_LIST_FAIL";

export const TRIP_DETAILS_REQUEST = "TRIP_DETAILS_REQUEST";
export const TRIP_DETAILS_SUCCESS = "TRIP_DETAILS_SUCCESS";
export const TRIP_DETAILS_FAIL = "TRIP_DETAILS_FAIL";

export const TRIP_DELETE_REQUEST = "TRIP_DELETE_REQUEST";
export const TRIP_DELETE_SUCCESS = "TRIP_DELETE_SUCCESS";
export const TRIP_DELETE_FAIL = "TRIP_DELETE_FAIL";

export const QUESTION_DELETE_REQUEST = "QUESTION_DELETE_REQUEST";
export const QUESTION_DELETE_SUCCESS = "QUESTION_DELETE_SUCCESS";
export const QUESTION_DELETE_FAIL = "QUESTION_DELETE_FAIL";
export const QUESTION_DELETE_RESET = "QUESTION_DELETE_RESET";

export const TRIP_CREATE_REQUEST = "TRIP_CREATE_REQUEST";
export const TRIP_CREATE_SUCCESS = "TRIP_CREATE_SUCCESS";
export const TRIP_CREATE_FAIL = "TRIP_CREATE_FAIL";
export const TRIP_CREATE_RESET = "TRIP_CREATE_RESET";

export const TRIP_UPDATE_REQUEST = "TRIP_UPDATE_REQUEST";
export const TRIP_UPDATE_SUCCESS = "TRIP_UPDATE_SUCCESS";
export const TRIP_UPDATE_FAIL = "TRIP_UPDATE_FAIL";
export const TRIP_UPDATE_RESET = "TRIP_UPDATE_RESET";

export const TRIP_CREATE_QUESTION_REQUEST = "TRIP_CREATE_QUESTION_REQUEST";
export const TRIP_CREATE_QUESTION_SUCCESS = "TRIP_CREATE_QUESTION_SUCCESS";
export const TRIP_CREATE_QUESTION_FAIL = "TRIP_CREATE_QUESTION_FAIL";
export const TRIP_CREATE_QUESTION_RESET = "TRIP_CREATE_QUESTION_RESET";
